import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AppLanguage = "en" | "ar" | "zh" | "hi" | "fr" | "es" | "pt";

type TranslationValue = string | string[];

type TranslationMap = Record<string, TranslationValue>;

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string) => TranslationValue;
}

const LANGUAGE_STORAGE_KEY = "skillswap_language";

const translations: Record<AppLanguage, TranslationMap> = {
  en: {
    "landing.searchPlaceholder": "Search for users",
    "landing.signIn": "Sign In",
    "landing.signUp": "Sign Up",
    "landing.start": "Find Your Partner",
    "landing.connectNew": "Connect with someone new",
    "landing.signInHint": "Sign in or create an account",
    "landing.nav.home": "Home",
    "landing.nav.features": "Features",
    "landing.nav.community": "Community",
    "landing.nav.about": "About",
    "landing.exploreFeatures": "Explore Features",
    "landing.subtitle": "Swap Skills · Grow Together · Connect with the World",
    "landing.features.title": "Empowering Meaningful Exchange",
    "landing.features.description": "Everything you need to master new skills and share your expertise through a seamless, interactive experience.",
    "landing.feature.video": "Crystal Clear Video",
    "landing.feature.videoDesc": "High-definition video calls optimized for remote teaching and real-time collaboration.",
    "landing.feature.chat": "Smart Real-time Chat",
    "landing.feature.chatDesc": "Instant messaging with file sharing and code snippet support to keep the conversation flowing.",
    "landing.feature.workspace": "Interactive Workspace",
    "landing.feature.workspaceDesc": "Built-in whiteboard and code editor for hands-on learning and technical demonstrations.",
    "landing.feature.games": "Mini-Games & Social",
    "landing.feature.gamesDesc": "Break the ice with integrated chess and other games while you wait or take a break.",
    "landing.feature.security": "Secure Connections",
    "landing.feature.securityDesc": "End-to-end encryption and robust privacy controls to ensure a safe learning environment.",
    "landing.feature.community": "Global Community",
    "landing.feature.communityDesc": "Connect with experts and enthusiasts from across the globe in seconds.",
    "landing.safety.title": "Safe & Moderated by AI",
    "landing.safety.desc": "Our platform takes immediate action against violators to ensure a safe learning environment using advanced AI moderation.",

    "landing.cta.title": "Ready to your skillest? Upgrade your skillest now",
    "landing.cta.highlightWord": "Upgrade",
    "landing.cta.description": "Join a community where knowledge is the currency. Swap what you know for what you want to learn. No fees, no barriers, just pure growth.",
    "landing.cta.button": "Join the Swap",
    "landing.cta.onlineUsers": "10,000+ Swappers Online",
    "landing.categories.artDesign": "Art & Design",
    "landing.categories.languages": "Languages",
    "landing.footer.tagline": "Empowering the next generation of lifelong learners through Peer-to-Peer skill exchange and global collaboration.",
    "landing.footer.product": "Product",
    "landing.footer.company": "Company",
    "landing.footer.features": "Features",
    "landing.footer.safety": "Safety",
    "landing.footer.enterprise": "Enterprise",
    "landing.footer.roadmap": "Roadmap",
    "landing.footer.about": "About Us",
    "landing.footer.privacy": "Privacy Policy",
    "landing.footer.terms": "Terms of Service",
    "landing.footer.contact": "Contact",
    "landing.footer.copyright": "© 2026 SkillSwap. All rights reserved.",
    "landing.footer.privacyLink": "Privacy",
    "landing.footer.termsLink": "Terms",
    "landing.footer.cookiesLink": "Cookies",
    "profileMenu.publicProfile": "Public profile",
    "profileMenu.settings": "Settings",
    "profileMenu.appearance": "Appearance",
    "profileMenu.accessibility": "Accessibility",
    "profileMenu.notifications": "Notifications",
    "profileMenu.signOut": "Sign Out",
    "profileMenu.feedback": "Develop SkillSwap",
    "landing.features.highlightWord": "Meaningful",
    "videochat.connected": "Connected",
    "videochat.lookingForMatch": "Looking for a match...",
    "videochat.cameraOff": "📷 Camera unavailable — joined with audio only",
    "videochat.chatHistory": "Chat history",
    "videochat.noMessages": "No messages yet",
    "videochat.you": "You",
    "videochat.them": "Them",
    "videochat.typeMessage": "Type...",
    "videochat.turnCameraOn": "Turn camera on",
    "videochat.turnCameraOff": "Turn camera off",
    "videochat.shareScreen": "Share Screen",
    "videochat.stopScreenShare": "Stop Screen Sharing",
    "videochat.screenSharing": "Screen Sharing",

    "videochat.watchTogether": "Watch together",
    "videochat.closeWatch": "Close watch mode",
    "videochat.codeWorkspace": "Code workspace (VS Code)",
    "videochat.closeCode": "Close code workspace",
    "videochat.whiteboard": "Whiteboard",
    "videochat.closeWhiteboard": "Close whiteboard",
    "videochat.chess": "3D Chess",
    "videochat.closeChess": "Close chess",
    "videochat.openChat": "Open chat",
    "videochat.closeChat": "Close chat",
    "videochat.volumeControl": "Volume control",
    "settings.title": "Settings",
    "settings.subtitle": "Manage your site preferences",
    "settings.languageTitle": "Site Language",
    "settings.languageDescription": "Choose the language used across the website interface.",
    "settings.themeTitle": "Theme",
    "settings.themeDescription": "Choose the visual mode for the website.",
    "settings.themeDark": "Dark",
    "settings.themeLight": "Light",
    "settings.english": "English",
    "settings.arabic": "Arabic",
    "settings.chinese": "Chinese",
    "settings.hindi": "Hindi",
    "settings.french": "French",
    "settings.spanish": "Spanish",
    "settings.portuguese": "Portuguese",
    "settings.saved": "Language saved successfully",
    "settings.back": "Back",
    "settings.securityTitle": "Security Dashboard",
    "settings.securityDescription": "Live monitoring of encryption, multi-path status, and active moderation."
  },
  ar: {
    "landing.searchPlaceholder": "البحث عن المستخدمين",
    "landing.signIn": "تسجيل الدخول",
    "landing.signUp": "إنشاء حساب",
    "landing.start": "ابدأ",
    "landing.connectNew": "اتصل بشخص جديد",
    "landing.signInHint": "سجّل الدخول أو أنشئ حسابًا",
    "landing.nav.home": "الرئيسية",
    "landing.nav.features": "المميزات",
    "landing.nav.community": "المجتمع",
    "landing.nav.about": "حول",
    "landing.exploreFeatures": "استكشف المميزات",
    "landing.subtitle": "تبادل المهارات · ننمو معاً · تواصل مع العالم",
    "landing.features.title": "تمكين التبادل عالي الجودة",
    "landing.features.description": "كل ما تحتاجه لإتقان مهارات جديدة ومشاركة خبرتك من خلال تجربة سلسة وتفاعلية.",
    "landing.feature.video": "فيديو واضح وعالي الجودة",
    "landing.feature.videoDesc": "مكالمات فيديو عالية الدقة محسّنة للتدريس عن بعد والتعاون في الوقت الفعلي.",
    "landing.feature.chat": "الدردشة الذكية الفورية",
    "landing.feature.chatDesc": "المراسلة الفورية مع مشاركة الملفات وشفرات البرنامج لإبقاء المحادثة مستمرة.",
    "landing.feature.workspace": "مساحة عمل تفاعلية",
    "landing.feature.workspaceDesc": "لوحة بيضاء مدمجة ومحرر أكواد للتعلم العملي والعروض التقنية.",
    "landing.feature.games": "الألعاب الصغيرة والتواصل الاجتماعي",
    "landing.feature.gamesDesc": "كسر الجليد بألعاب الشطرنج والألعاب الأخرى أثناء الانتظار أو الاستراحة.",
    "landing.feature.security": "اتصالات آمنة",
    "landing.feature.securityDesc": "تشفير من طرف إلى طرف وضوابط خصوصية قوية لضمان بيئة تعليمية آمنة.",
    "landing.feature.community": "مجتمع عالمي",
    "landing.feature.communityDesc": "تواصل مع الخبراء والمتحمسين من جميع أنحاء العالم في ثوانٍ.",
    "landing.safety.title": "آمن وخاضع لإشراف الذكاء الاصطناعي",
    "landing.safety.desc": "تتخذ منصتنا إجراءات فورية ضد الحسابات المخالفة لتشجيع بيئة تعليمية آمنة باستخدام تقنيات الذكاء الاصطناعي.",

    "landing.cta.title": "هل أنت مستعد لتحسين مهاراتك؟",
    "landing.cta.highlightWord": "لتحسين",
    "landing.cta.description": "انضم إلى مجتمع حيث المعرفة هي العملة. تبادل ما تعرفه بما تريد تعلمه. لا رسوم، لا حواجز، فقط نمو حقيقي.",
    "landing.cta.button": "انضم إلى التبادل",
    "landing.cta.onlineUsers": "أكثر من 10,000 مبادل نشط حالياً",
    "landing.categories.artDesign": "الفن والتصميم",
    "landing.categories.languages": "اللغات",
    "landing.footer.tagline": "تمكين الجيل القادم من متعلمي الحياة الدائمة من خلال تبادل المهارات من نظير إلى نظير والتعاون العالمي.",
    "landing.footer.product": "المنتج",
    "landing.footer.company": "الشركة",
    "landing.footer.features": "المميزات",
    "landing.footer.safety": "الأمان",
    "landing.footer.enterprise": "للشركات",
    "landing.footer.roadmap": "الخارطة الطريقية",
    "landing.footer.about": "من نحن",
    "landing.footer.privacy": "سياسة الخصوصية",
    "landing.footer.terms": "شروط الخدمة",
    "landing.footer.contact": "التواصل",
    "landing.footer.copyright": "© 2026 سكيل سواب. جميع الحقوق محفوظة.",
    "landing.footer.privacyLink": "الخصوصية",
    "landing.footer.termsLink": "الشروط",
    "landing.footer.cookiesLink": "ملفات تعريف الارتباط",
    "profileMenu.publicProfile": "الملف العام",
    "profileMenu.settings": "الإعدادات",
    "profileMenu.appearance": "المظهر",
    "profileMenu.accessibility": "إمكانية الوصول",
    "profileMenu.notifications": "الإشعارات",
    "profileMenu.signOut": "تسجيل الخروج",
    "profileMenu.feedback": "تطوير سكلسواب",
    "landing.features.highlightWord": "عالي الجودة",
    "videochat.connected": "متصل",
    "videochat.lookingForMatch": "جاري البحث عن شريك...",
    "videochat.cameraOff": "📷 الكاميرا غير متاحة — منضم بالصوت فقط",
    "videochat.chatHistory": "سجل الدردشة",
    "videochat.noMessages": "لا توجد رسائل بعد",
    "videochat.you": "أنت",
    "videochat.them": "الآخر",
    "videochat.typeMessage": "اكتب...",
    "videochat.turnCameraOn": "تشغيل الكاميرا",
    "videochat.turnCameraOff": "إيقاف الكاميرا",
    "videochat.shareScreen": "مشاركة الشاشة",
    "videochat.stopScreenShare": "إيقاف مشاركة الشاشة",
    "videochat.screenSharing": "مشاركة الشاشة",

    "videochat.watchTogether": "المشاهدة معاً",
    "videochat.closeWatch": "إغلاق المشاهدة",
    "videochat.codeWorkspace": "مساحة الأكواد (VS Code)",
    "videochat.closeCode": "إغلاق مساحة الأكواد",
    "videochat.whiteboard": "اللوحة البيضاء",
    "videochat.closeWhiteboard": "إغلاق اللوحة البيضاء",
    "videochat.chess": "شطرنج ثلاثي الأبعاد",
    "videochat.closeChess": "إغلاق الشطرنج",
    "videochat.openChat": "فتح الدردشة",
    "videochat.closeChat": "إغلاق الدردشة",
    "videochat.volumeControl": "التحكم في مستوى الصوت",
    "settings.title": "الإعدادات",
    "settings.subtitle": "إدارة تفضيلات الموقع",
    "settings.languageTitle": "لغة الموقع",
    "settings.languageDescription": "اختر اللغة المستخدمة في واجهة الموقع.",
    "settings.themeTitle": "الثيم",
    "settings.themeDescription": "اختر النمط البصري للموقع.",
    "settings.themeDark": "غامق",
    "settings.themeLight": "فاتح",
    "settings.english": "الإنجليزية",
    "settings.arabic": "العربية",
    "settings.chinese": "الصينية",
    "settings.hindi": "الهندية",
    "settings.french": "الفرنسية",
    "settings.spanish": "الإسبانية",
    "settings.portuguese": "البرتغالية",
    "settings.saved": "تم حفظ اللغة بنجاح",
    "settings.back": "رجوع",
    "settings.securityTitle": "لوحة تحكم الأمان",
    "settings.securityDescription": "مراقبة حية للتشفير، حالة المسارات المتعددة، والرصد النشط."
  },
  zh: {
    "landing.searchPlaceholder": "按姓名或电子邮件搜索用户...",
    "landing.signIn": "登录",
    "landing.signUp": "注册",
    "landing.start": "开始",
    "landing.connectNew": "结识新朋友",
    "landing.signInHint": "登录或创建账户",
    "landing.nav.home": "首页",
    "landing.nav.features": "功能",
    "landing.nav.community": "社区",
    "landing.nav.about": "关于",
    "landing.exploreFeatures": "探索功能",
    "landing.subtitle": "交流技能 · 共同成长 · 连接世界",
    "landing.features.title": "赋能有意义的交流",
    "landing.features.description": "掌握新技能和分享专业知识所需的一切，尽在无缝的互动体验中。",
    "landing.feature.video": "清晰视频",
    "landing.feature.videoDesc": "专为远程教学和实时协作优化的超清视频通话。",
    "landing.feature.chat": "智能实时聊天",
    "landing.feature.chatDesc": "支持文件共享和代码片段的即时消息，让对话畅通无阻。",
    "landing.feature.workspace": "互动工作区",
    "landing.feature.workspaceDesc": "内置白板和代码编辑器，适合动手学习和技术演示。",
    "landing.feature.games": "小游戏与社交",
    "landing.feature.gamesDesc": "在等待或休息时通过国际象棋等游戏打破僵局。",
    "landing.feature.security": "安全连接",
    "landing.feature.securityDesc": "端到端加密和强大的隐私控制，确保安全的学习环境。",
    "landing.feature.community": "全球社区",
    "landing.feature.communityDesc": "在几秒钟内与来自世界各地的专家和爱好者建立联系。",
    "landing.safety.title": "由AI监控保障安全",
    "landing.safety.desc": "我们的平台采用先进的AI监控系统，对违规行为立即采取行动，以确保安全的学习环境。",
    "landing.cta.title": "准备好提升您的技能了吗？",
    "landing.cta.highlightWord": "提升",
    "landing.cta.description": "加入一个以知识为货币的社区。用您所知换取您想学的。没有费用，没有障碍，只有纯粹的成长。",
    "landing.cta.button": "加入交流",
    "landing.cta.onlineUsers": "10,000+ 用户在线",
    "landing.categories.artDesign": "艺术与设计",
    "landing.categories.languages": "语言",
    "landing.footer.tagline": "通过点对点技能交流和全球协作，赋能下一代终身学习者。",
    "landing.footer.product": "产品",
    "landing.footer.company": "公司",
    "landing.footer.features": "功能",
    "landing.footer.safety": "安全",
    "landing.footer.enterprise": "企业",
    "landing.footer.roadmap": "路线图",
    "landing.footer.about": "关于我们",
    "landing.footer.privacy": "隐私政策",
    "landing.footer.terms": "服务条款",
    "landing.footer.contact": "联系我们",
    "landing.footer.copyright": "© 2026 SkillSwap。保留所有权利。",
    "landing.footer.privacyLink": "隐私",
    "landing.footer.termsLink": "条款",
    "landing.footer.cookiesLink": "Cookie",
    "profileMenu.publicProfile": "公开资料",
    "profileMenu.settings": "设置",
    "profileMenu.appearance": "外观",
    "profileMenu.accessibility": "无障碍",
    "profileMenu.notifications": "通知",
    "profileMenu.signOut": "退出登录",
    "profileMenu.feedback": "开发 SkillSwap",
    "landing.features.highlightWord": "有意义的",
    "videochat.connected": "已连接",
    "videochat.lookingForMatch": "正在寻找匹配...",
    "videochat.cameraOff": "📷 摄像头不可用 — 仅语音加入",
    "videochat.chatHistory": "聊天记录",
    "videochat.noMessages": "暂无消息",
    "videochat.you": "你",
    "videochat.them": "对方",
    "videochat.typeMessage": "输入...",
    "videochat.turnCameraOn": "开启摄像头",
    "videochat.turnCameraOff": "关闭摄像头",
    "videochat.shareScreen": "共享屏幕",
    "videochat.stopScreenShare": "停止共享屏幕",
    "videochat.screenSharing": "屏幕共享中",

    "videochat.watchTogether": "一起观看",
    "videochat.closeWatch": "关闭观看模式",
    "videochat.codeWorkspace": "代码工作区 (VS Code)",
    "videochat.closeCode": "关闭代码工作区",
    "videochat.whiteboard": "白板",
    "videochat.closeWhiteboard": "关闭白板",
    "videochat.chess": "3D 国际象棋",
    "videochat.closeChess": "关闭国际象棋",
    "videochat.openChat": "打开聊天",
    "videochat.closeChat": "关闭聊天",
    "videochat.volumeControl": "音量控制",
    "settings.title": "设置",
    "settings.subtitle": "管理您的站点偏好",
    "settings.languageTitle": "网站语言",
    "settings.languageDescription": "选择界面使用的语言。",
    "settings.themeTitle": "主题",
    "settings.themeDescription": "选择网站的视觉模式。",
    "settings.themeDark": "深色",
    "settings.themeLight": "浅色",
    "settings.english": "英语",
    "settings.arabic": "阿拉伯语",
    "settings.chinese": "中文",
    "settings.hindi": "印地语",
    "settings.french": "法语",
    "settings.spanish": "西班牙语",
    "settings.portuguese": "葡萄牙语",
    "settings.saved": "语言保存成功",
    "settings.back": "返回"
  },
  hi: {
    "landing.searchPlaceholder": "नाम या ईमेल द्वारा उपयोगकर्ताओं को खोजें...",
    "landing.signIn": "साइन इन करें",
    "landing.signUp": "साइन अप करें",
    "landing.start": "शुरू करें",
    "landing.connectNew": "किसी नए व्यक्ति से जुड़ें",
    "landing.signInHint": "साइन इन करें या खाता बनाएं",
    "landing.nav.home": "होम",
    "landing.nav.features": "विशेषताएं",
    "landing.nav.community": "समुदाय",
    "landing.nav.about": "हमारे बारे में",
    "landing.exploreFeatures": "विशेषताएं एक्सप्लोर करें",
    "landing.subtitle": "कौशल बदलें · एक साथ बढ़ें · दुनिया से जुड़ें",
    "landing.features.title": "सार्थक आदान-प्रदान को सशक्त बनाना",
    "landing.features.description": "एक सहज, संवादात्मक अनुभव के माध्यम से नए कौशल में महारत हासिल करने और अपनी विशेषज्ञता साझा करने के लिए आपकी ज़रूरत की हर चीज़।",
    "landing.feature.video": "क्रिस्टल क्लियर वीडियो",
    "landing.feature.videoDesc": "रिमोट शिक्षण और वास्तविक समय के सहयोग के लिए अनुकूलित उच्च-परिभाषा वीडियो कॉल।",
    "landing.feature.chat": "स्मार्ट रियल-टाइम चैट",
    "landing.feature.chatDesc": "बातचीत को जारी रखने के लिए फ़ाइल साझाकरण और कोड स्निपेट समर्थन के साथ त्वरित संदेश।",
    "landing.feature.workspace": "इंटरएक्टिव कार्यक्षेत्र",
    "landing.feature.workspaceDesc": "व्यावहारिक शिक्षण और तकनीकी प्रदर्शनों के लिए अंतर्निहित व्हाइटबोर्ड और कोड संपादक।",
    "landing.feature.games": "मिनी-गेम्स और सोशल",
    "landing.feature.gamesDesc": "इंतजार करते समय या ब्रेक लेते समय एकीकृत शतरंज और अन्य खेलों के साथ बर्फ तोड़ें।",
    "landing.feature.security": "सुरक्षित कनेक्शन",
    "landing.feature.securityDesc": "एक सुरक्षित शिक्षण वातावरण सुनिश्चित करने के लिए एंड-टू-एंड एन्क्रिप्शन और मजबूत गोपनीयता नियंत्रण।",
    "landing.feature.community": "वैश्विक समुदाय",
    "landing.feature.communityDesc": "कुछ ही सेकंड में दुनिया भर के विशेषज्ञों और उत्साही लोगों से जुड़ें।",
    "landing.safety.title": "AI द्वारा सुरक्षित और मॉडरेट किया गया",
    "landing.safety.desc": "हमारा मंच उन्नत एआई मॉडरेशन का उपयोग करके एक सुरक्षित सीखने के माहौल को सुनिश्चित करने के लिए उल्लंघनकर्ताओं के खिलाफ तत्काल कार्रवाई करता है।",
    "landing.cta.title": "क्या आप अपने कौशल को अपग्रेड करने के लिए तैयार हैं?",
    "landing.cta.highlightWord": "अपग्रेड",
    "landing.cta.description": "एक ऐसे समुदाय में शामिल हों जहाँ ज्ञान ही मुद्रा है। जो आप जानते हैं उसे उस चीज़ के लिए बदलें जो आप सीखना चाहते हैं। कोई शुल्क नहीं, कोई बाधा नहीं, बस शुद्ध विकास।",
    "landing.cta.button": "स्वैप में शामिल हों",
    "landing.cta.onlineUsers": "10,000+ स्वैपर्स ऑनलाइन",
    "landing.categories.artDesign": "कला और डिज़ाइन",
    "landing.categories.languages": "भाषाएँ",
    "landing.footer.tagline": "पीयर-टू-पीयर कौशल विनिमय और वैश्विक सहयोग के माध्यम से आजीवन सीखने वालों की अगली पीढ़ी को सशक्त बनाना।",
    "landing.footer.product": "उत्पाद",
    "landing.footer.company": "कंपनी",
    "landing.footer.features": "विशेषताएं",
    "landing.footer.safety": "सुरक्षा",
    "landing.footer.enterprise": "उद्यम",
    "landing.footer.roadmap": "रोडमैप",
    "landing.footer.about": "हमारे बारे में",
    "landing.footer.privacy": "गोपनीयता नीति",
    "landing.footer.terms": "सेवा की शर्तें",
    "landing.footer.contact": "संपर्क करें",
    "landing.footer.copyright": "© 2026 SkillSwap। सर्वाधिकार सुरक्षित।",
    "landing.footer.privacyLink": "गोपनीयता",
    "landing.footer.termsLink": "शर्तें",
    "landing.footer.cookiesLink": "कुकीज़",
    "profileMenu.publicProfile": "सार्वजनिक प्रोफ़ाइल",
    "profileMenu.settings": "सेटिंग्स",
    "profileMenu.appearance": "दिखावट",
    "profileMenu.accessibility": "पहुंच",
    "profileMenu.notifications": "सूचनाएं",
    "profileMenu.signOut": "साइन आउट",
    "profileMenu.feedback": "स्किलस्वैप विकसित करें",
    "landing.features.highlightWord": "सार्थक",
    "videochat.connected": "जुड़ा हुआ",
    "videochat.lookingForMatch": "मैच खोज रहे हैं...",
    "videochat.cameraOff": "📷 कैमरा अनुपलब्ध — केवल ऑडियो के साथ जुड़े",
    "videochat.chatHistory": "चैट इतिहास",
    "videochat.noMessages": "अभी तक कोई संदेश नहीं",
    "videochat.you": "आप",
    "videochat.them": "वे",
    "videochat.typeMessage": "टाइप करें...",
    "videochat.turnCameraOn": "कैमरा चालू करें",
    "videochat.turnCameraOff": "कैमरा बंद करें",
    "videochat.shareScreen": "स्क्रीन साझा करें",
    "videochat.stopScreenShare": "स्क्रीन साझा करना बंद करें",
    "videochat.screenSharing": "स्क्रीन शेयरिंग",

    "videochat.watchTogether": "एक साथ देखें",
    "videochat.closeWatch": "वॉच मोड बंद करें",
    "videochat.codeWorkspace": "कोड कार्यक्षेत्र (VS Code)",
    "videochat.closeCode": "कोड कार्यक्षेत्र बंद करें",
    "videochat.whiteboard": "व्हाइटबोर्ड",
    "videochat.closeWhiteboard": "व्हाइटबोर्ड बंद करें",
    "videochat.chess": "3D शतरंज",
    "videochat.closeChess": "शतरंज बंद करें",
    "videochat.openChat": "चैट खोलें",
    "videochat.closeChat": "चैट बंद करें",
    "videochat.volumeControl": "वॉल्यूम नियंत्रण",
    "settings.title": "सेटिंग्स",
    "settings.subtitle": "अपनी साइट वरीयताओं को प्रबंधित करें",
    "settings.languageTitle": "साइट की भाषा",
    "settings.languageDescription": "वेबसाइट इंटरफ़ेस में उपयोग की जाने वाली भाषा चुनें।",
    "settings.themeTitle": "थीम",
    "settings.themeDescription": "वेबसाइट के लिए दृश्य मोड चुनें।",
    "settings.themeDark": "डार्क",
    "settings.themeLight": "लाइट",
    "settings.english": "अंग्रेज़ी",
    "settings.arabic": "अरबी",
    "settings.chinese": "चीनी",
    "settings.hindi": "हिंदी",
    "settings.french": "फ़्रेंच",
    "settings.spanish": "स्पेनी",
    "settings.portuguese": "पुर्तगाली",
    "settings.saved": "भाषा सफलतापूर्वक सहेजी गई",
    "settings.back": "वापस"
  },
  fr: {
    "landing.searchPlaceholder": "Rechercher des utilisateurs par nom ou email...",
    "landing.signIn": "Se connecter",
    "landing.signUp": "S'inscrire",
    "landing.start": "Démarrer",
    "landing.connectNew": "Se connecter avec quelqu'un",
    "landing.signInHint": "Connectez-vous ou créez un compte",
    "landing.nav.home": "Accueil",
    "landing.nav.features": "Fonctionnalités",
    "landing.nav.community": "Communauté",
    "landing.nav.about": "À propos",
    "landing.exploreFeatures": "Explorer les fonctionnalités",
    "landing.subtitle": "Échangez vos compétences · Grandissez ensemble · Connectez-vous",
    "landing.features.title": "Favoriser des échanges enrichissants",
    "landing.features.description": "Tout ce dont vous avez besoin pour maîtriser de nouvelles compétences et partager votre expertise via une expérience fluide.",
    "landing.feature.video": "Vidéo cristalline",
    "landing.feature.videoDesc": "Appels vidéo haute définition optimisés pour l'enseignement à distance et la collaboration.",
    "landing.feature.chat": "Chat intelligent",
    "landing.feature.chatDesc": "Messagerie instantanée avec partage de fichiers et d'extraits de code.",
    "landing.feature.workspace": "Espace interactif",
    "landing.feature.workspaceDesc": "Tableau blanc et éditeur de code intégrés pour les démonstrations techniques.",
    "landing.feature.games": "Mini-jeux et Social",
    "landing.feature.gamesDesc": "Brisez la glace avec des échecs et d'autres jeux en attendant.",
    "landing.feature.security": "Connexions sécurisées",
    "landing.feature.securityDesc": "Chiffrement de bout en bout et contrôles de confidentialité.",
    "landing.feature.community": "Communauté mondiale",
    "landing.feature.communityDesc": "Connectez-vous en quelques secondes avec des passionnés du monde entier.",
    "landing.safety.title": "Sécurisé et modéré par l'IA",
    "landing.safety.desc": "Notre plateforme prend des mesures immédiates contre les contrevenants pour garantir un environnement d'apprentissage sûr grâce à une modération IA avancée.",
    "landing.cta.title": "Prêt à améliorer vos compétences ?",
    "landing.cta.highlightWord": "Améliorer",
    "landing.cta.description": "Rejoignez une communauté ou la monnaie c'est la connaissance. Pas de frais, pas de barrières, juste de la croissance.",
    "landing.cta.button": "Rejoindre l'échange",
    "landing.cta.onlineUsers": "10 000+ utilisateurs en ligne",
    "landing.categories.artDesign": "Art & Design",
    "landing.categories.languages": "Langues",
    "landing.footer.tagline": "Donner aux apprenants de demain les moyens de collaborer et d'échanger.",
    "landing.footer.product": "Produit",
    "landing.footer.company": "Entreprise",
    "landing.footer.features": "Fonctionnalités",
    "landing.footer.safety": "Sécurité",
    "landing.footer.enterprise": "Entreprise",
    "landing.footer.roadmap": "Feuille de route",
    "landing.footer.about": "À propos",
    "landing.footer.privacy": "Confidentialité",
    "landing.footer.terms": "Conditions d'utilisation",
    "landing.footer.contact": "Contact",
    "landing.footer.copyright": "© 2026 SkillSwap. Tous droits réservés.",
    "landing.footer.privacyLink": "Confidentialité",
    "landing.footer.termsLink": "Conditions",
    "landing.footer.cookiesLink": "Cookies",
    "profileMenu.publicProfile": "Profil public",
    "profileMenu.settings": "Paramètres",
    "profileMenu.appearance": "Apparence",
    "profileMenu.accessibility": "Accessibilité",
    "profileMenu.notifications": "Notifications",
    "profileMenu.signOut": "Déconnexion",
    "profileMenu.feedback": "Développer SkillSwap",
    "landing.features.highlightWord": "enrichissants",
    "videochat.connected": "Connecté",
    "videochat.lookingForMatch": "Recherche d'un partenaire...",
    "videochat.cameraOff": "📷 Caméra non disponible — rejoint avec l'audio uniquement",
    "videochat.chatHistory": "Historique du chat",
    "videochat.noMessages": "Aucun message pour l'instant",
    "videochat.you": "Vous",
    "videochat.them": "Eux",
    "videochat.typeMessage": "Taper...",
    "videochat.turnCameraOn": "Activer la caméra",
    "videochat.turnCameraOff": "Désactiver la caméra",
    "videochat.shareScreen": "Partager l'écran",
    "videochat.stopScreenShare": "Arrêter le partage d'écran",
    "videochat.screenSharing": "Partage d'écran",

    "videochat.watchTogether": "Regarder ensemble",
    "videochat.closeWatch": "Fermer le mode visionnage",
    "videochat.codeWorkspace": "Espace de code (VS Code)",
    "videochat.closeCode": "Fermer l'espace de code",
    "videochat.whiteboard": "Tableau blanc",
    "videochat.closeWhiteboard": "Fermer le tableau blanc",
    "videochat.chess": "Échecs 3D",
    "videochat.closeChess": "Fermer les échecs",
    "videochat.openChat": "Ouvrir le chat",
    "videochat.closeChat": "Fermer le chat",
    "videochat.volumeControl": "Contrôle du volume",
    "settings.title": "Paramètres",
    "settings.subtitle": "Gérer vos préférences",
    "settings.languageTitle": "Langue",
    "settings.languageDescription": "Choisissez la langue de l'interface.",
    "settings.themeTitle": "Thème",
    "settings.themeDescription": "Choisissez le mode visuel.",
    "settings.themeDark": "Sombre",
    "settings.themeLight": "Clair",
    "settings.english": "Anglais",
    "settings.arabic": "Arabe",
    "settings.chinese": "Chinois",
    "settings.hindi": "Hindi",
    "settings.french": "Français",
    "settings.spanish": "Espagnol",
    "settings.portuguese": "Portugais",
    "settings.saved": "Langue enregistrée",
    "settings.back": "Retour"
  },
  es: {
    "landing.searchPlaceholder": "Buscar usuarios por nombre o correo...",
    "landing.signIn": "Iniciar sesión",
    "landing.signUp": "Registrarse",
    "landing.start": "Comenzar",
    "landing.connectNew": "Conectar con alguien nuevo",
    "landing.signInHint": "Inicia sesión o crea una cuenta",
    "landing.nav.home": "Inicio",
    "landing.nav.features": "Características",
    "landing.nav.community": "Comunidad",
    "landing.nav.about": "Acerca de",
    "landing.exploreFeatures": "Explorar funciones",
    "landing.subtitle": "Intercambia habilidades · Crece · Conecta con el mundo",
    "landing.features.title": "Empoderando intercambios significativos",
    "landing.features.description": "Todo lo que necesitas para dominar nuevas habilidades a través de una experiencia interactiva.",
    "landing.feature.video": "Video nítido",
    "landing.feature.videoDesc": "Llamadas de alta definición optimizadas para enseñanza y colaboración.",
    "landing.feature.chat": "Chat inteligente",
    "landing.feature.chatDesc": "Mensajes con intercambio de archivos y bloques de código.",
    "landing.feature.workspace": "Espacio de trabajo",
    "landing.feature.workspaceDesc": "Pizarra y editor de código para aprendizaje práctico.",
    "landing.feature.games": "Minijuegos y social",
    "landing.feature.gamesDesc": "Rompe el hielo con ajedrez y otros juegos mientras esperas.",
    "landing.feature.security": "Conexiones seguras",
    "landing.feature.securityDesc": "Cifrado de extremo a extremo para garantizar la privacidad.",
    "landing.feature.community": "Comunidad global",
    "landing.feature.communityDesc": "Conecta con expertos de todo el mundo en segundos.",
    "landing.safety.title": "Seguro y moderado por IA",
    "landing.safety.desc": "Nuestra plataforma toma medidas inmediatas contra los infractores para garantizar un entorno de aprendizaje seguro utilizando moderación avanzada de IA.",
    "landing.cta.title": "¿Listo para mejorar tus habilidades?",
    "landing.cta.highlightWord": "Mejorar",
    "landing.cta.description": "Únete a una comunidad donde el conocimiento es la moneda. Sin tarifas, sin barreras, solo crecimiento.",
    "landing.cta.button": "Únete al intercambio",
    "landing.cta.onlineUsers": "10,000+ usuarios en línea",
    "landing.categories.artDesign": "Arte y Diseño",
    "landing.categories.languages": "Idiomas",
    "landing.footer.tagline": "Empoderando a la próxima generación mediante el intercambio de habilidades.",
    "landing.footer.product": "Producto",
    "landing.footer.company": "Compañía",
    "landing.footer.features": "Características",
    "landing.footer.safety": "Seguridad",
    "landing.footer.enterprise": "Empresa",
    "landing.footer.roadmap": "Hoja de ruta",
    "landing.footer.about": "Acerca de",
    "landing.footer.privacy": "Privacidad",
    "landing.footer.terms": "Términos de servicio",
    "landing.footer.contact": "Contacto",
    "landing.footer.copyright": "© 2026 SkillSwap. Todos los derechos reservados.",
    "landing.footer.privacyLink": "Privacidad",
    "landing.footer.termsLink": "Términos",
    "landing.footer.cookiesLink": "Cookies",
    "profileMenu.publicProfile": "Perfil público",
    "profileMenu.settings": "Configuración",
    "profileMenu.appearance": "Apariencia",
    "profileMenu.accessibility": "Accesibilidad",
    "profileMenu.notifications": "Notificaciones",
    "profileMenu.signOut": "Cerrar sesión",
    "profileMenu.feedback": "Desarrollar SkillSwap",
    "landing.features.highlightWord": "significativos",
    "videochat.connected": "Conectado",
    "videochat.lookingForMatch": "Buscando una coincidencia...",
    "videochat.cameraOff": "📷 Cámara no disponible — unido solo con audio",
    "videochat.chatHistory": "Historial de chat",
    "videochat.noMessages": "No hay mensajes aún",
    "videochat.you": "Tú",
    "videochat.them": "Ellos",
    "videochat.typeMessage": "Escribir...",
    "videochat.turnCameraOn": "Encender cámara",
    "videochat.turnCameraOff": "Apagar cámara",
    "videochat.shareScreen": "Compartir pantalla",
    "videochat.stopScreenShare": "Dejar de compartir",
    "videochat.screenSharing": "Compartiendo pantalla",

    "videochat.watchTogether": "Ver juntos",
    "videochat.closeWatch": "Cerrar modo visualización",
    "videochat.codeWorkspace": "Espacio de código (VS Code)",
    "videochat.closeCode": "Cerrar espacio de trabajo",
    "videochat.whiteboard": "Pizarra",
    "videochat.closeWhiteboard": "Cerrar pizarra",
    "videochat.chess": "Ajedrez 3D",
    "videochat.closeChess": "Cerrar ajedrez",
    "videochat.openChat": "Abrir chat",
    "videochat.closeChat": "Cerrar chat",
    "videochat.volumeControl": "Control de volumen",
    "settings.title": "Configuración",
    "settings.subtitle": "Administra las preferencias del sitio",
    "settings.languageTitle": "Idioma",
    "settings.languageDescription": "Elige el idioma de la interfaz del sitio web.",
    "settings.themeTitle": "Tema",
    "settings.themeDescription": "Elige el modo visual del sitio web.",
    "settings.themeDark": "Oscuro",
    "settings.themeLight": "Claro",
    "settings.english": "Inglés",
    "settings.arabic": "Árabe",
    "settings.chinese": "Chino",
    "settings.hindi": "Hindi",
    "settings.french": "Francés",
    "settings.spanish": "Español",
    "settings.portuguese": "Portugués",
    "settings.saved": "Idioma guardado",
    "settings.back": "Volver"
  },
  pt: {
    "landing.searchPlaceholder": "Buscar usuários por nome ou email...",
    "landing.signIn": "Entrar",
    "landing.signUp": "Cadastrar",
    "landing.start": "Começar",
    "landing.connectNew": "Conectar com alguém",
    "landing.signInHint": "Entre ou crie uma conta",
    "landing.nav.home": "Início",
    "landing.nav.features": "Recursos",
    "landing.nav.community": "Comunidade",
    "landing.nav.about": "Sobre",
    "landing.exploreFeatures": "Explorar Recursos",
    "landing.subtitle": "Troque Habilidades · Cresçam Juntos · Conecte-se",
    "landing.features.title": "Capacitando Trocas Significativas",
    "landing.features.description": "Tudo que você precisa para dominar novas habilidades e compartilhar.",
    "landing.feature.video": "Vídeo Cristalino",
    "landing.feature.videoDesc": "Chamadas de vídeo de alta definição otimizadas para ensino.",
    "landing.feature.chat": "Chat Inteligente",
    "landing.feature.chatDesc": "Mensagens instantâneas com compartilhamento de arquivos e código.",
    "landing.feature.workspace": "Espaço de Trabalho",
    "landing.feature.workspaceDesc": "Quadro branco e editor de código integrados para aprendizado prático.",
    "landing.feature.games": "Minijogos e Social",
    "landing.feature.gamesDesc": "Quebre o gelo com xadrez e outros jogos enquanto espera.",
    "landing.feature.security": "Conexões Seguras",
    "landing.feature.securityDesc": "Criptografia de ponta a ponta para garantir a privacidade.",
    "landing.feature.community": "Comunidade Global",
    "landing.feature.communityDesc": "Conecte-se com especialistas do mundo todo em segundos.",
    "landing.safety.title": "Seguro e moderado por IA",
    "landing.safety.desc": "Nossa plataforma toma medidas imediatas contra infratores para garantir um ambiente de aprendizado seguro usando moderação avançada de IA.",
    "landing.cta.title": "Pronto para melhorar suas habilidades?",
    "landing.cta.highlightWord": "Melhorar",
    "landing.cta.description": "Junte-se a uma comunidade onde o conhecimento é a moeda. Sem taxas, sem barreiras, apenas crescimento.",
    "landing.cta.button": "Junte-se à Troca",
    "landing.cta.onlineUsers": "10,000+ usuários online",
    "landing.categories.artDesign": "Arte & Design",
    "landing.categories.languages": "Idiomas",
    "landing.footer.tagline": "Fortalecendo a próxima geração por meio da troca de habilidades.",
    "landing.footer.product": "Produto",
    "landing.footer.company": "Empresa",
    "landing.footer.features": "Recursos",
    "landing.footer.safety": "Segurança",
    "landing.footer.enterprise": "Empresarial",
    "landing.footer.roadmap": "Roteiro",
    "landing.footer.about": "Sobre Nós",
    "landing.footer.privacy": "Privacidade",
    "landing.footer.terms": "Termos de Serviço",
    "landing.footer.contact": "Contato",
    "landing.footer.copyright": "© 2026 SkillSwap. Todos os direitos reservados.",
    "landing.footer.privacyLink": "Privacidade",
    "landing.footer.termsLink": "Termos",
    "landing.footer.cookiesLink": "Cookies",
    "profileMenu.publicProfile": "Perfil público",
    "profileMenu.settings": "Configurações",
    "profileMenu.appearance": "Aparência",
    "profileMenu.accessibility": "Acessibilidade",
    "profileMenu.notifications": "Notificações",
    "profileMenu.signOut": "Sair",
    "profileMenu.feedback": "Desenvolver SkillSwap",
    "landing.features.highlightWord": "Significativas",
    "videochat.connected": "Conectado",
    "videochat.lookingForMatch": "Procurando correspondência...",
    "videochat.cameraOff": "📷 Câmera indisponível — entrou apenas com áudio",
    "videochat.chatHistory": "Histórico de chat",
    "videochat.noMessages": "Sem mensagens ainda",
    "videochat.you": "Você",
    "videochat.them": "Eles",
    "videochat.typeMessage": "Digitar...",
    "videochat.turnCameraOn": "Ligar câmera",
    "videochat.turnCameraOff": "Desligar câmera",
    "videochat.shareScreen": "Compartilhar tela",
    "videochat.stopScreenShare": "Parar de compartilhar",
    "videochat.screenSharing": "Compartilhamento de tela",

    "videochat.watchTogether": "Assistir juntos",
    "videochat.closeWatch": "Fechar modo de exibição",
    "videochat.codeWorkspace": "Espaço de código (VS Code)",
    "videochat.closeCode": "Fechar espaço de código",
    "videochat.whiteboard": "Quadro branco",
    "videochat.closeWhiteboard": "Fechar quadro branco",
    "videochat.chess": "Xadrez 3D",
    "videochat.closeChess": "Fechar xadrez",
    "videochat.openChat": "Abrir chat",
    "videochat.closeChat": "Fechar chat",
    "videochat.volumeControl": "Controle de volume",
    "settings.title": "Configurações",
    "settings.subtitle": "Gerencie suas preferências",
    "settings.languageTitle": "Idioma",
    "settings.languageDescription": "Escolha o idioma usado na interface do site.",
    "settings.themeTitle": "Tema",
    "settings.themeDescription": "Escolha o modo visual do site.",
    "settings.themeDark": "Escuro",
    "settings.themeLight": "Claro",
    "settings.english": "Inglês",
    "settings.arabic": "Árabe",
    "settings.chinese": "Chinês",
    "settings.hindi": "Hindi",
    "settings.french": "Francês",
    "settings.spanish": "Espanhol",
    "settings.portuguese": "Português",
    "settings.saved": "Idioma salvo",
    "settings.back": "Voltar"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (saved === "ar" || saved === "zh" || saved === "hi" || saved === "fr" || saved === "es" || saved === "pt") {
      return saved as AppLanguage;
    }
    return "en";
  });

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const setLanguage = (nextLanguage: AppLanguage) => {
    setLanguageState(nextLanguage);
  };

  const value = useMemo<LanguageContextType>(() => {
    return {
      language,
      setLanguage,
      t: (key: string): TranslationValue => {
        return translations[language][key] ?? translations.en[key] ?? key;
      }
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }

  return context;
}
